[package]
name = "console-api"
version = "0.1.0"
edition = "2018"
license = "MIT"

[features]
# Generate code that is compatible with Tonic's `transport` module.
transport = ["tonic-build/transport", "tonic/transport"]

[dependencies]
tonic = { version = "0.6", default-features = false, features = [
    "prost",
    "codegen",
] }
prost = "0.9"
prost-types = "0.9"
tracing-core = "0.1.17"

[build-dependencies]
tonic-build = { version = "0.6", default-features = false, features = [
    "prost",
] }
