[package]
name = "console-api"
version = "0.1.0"
authors = ["Eliza Weisman <eliza@buoyant.io>"]
edition = "2018"
[features]
# Generate code that is compatible with Tonic's `transport` module.
transport = ["tonic-build/transport", "tonic/transport"]

[dependencies]
tonic = { version = "0.5", default-features = false, features = [
    "prost",
    "codegen",
] }
prost = "0.8"
prost-types = "0.8"
tracing-core = "0.1.17"

[build-dependencies]
tonic-build = { version = "0.5", default-features = false, features = [
    "prost",
] }
