[package]
name = "console-subscriber"
version = "0.1.0"
authors = ["Eliza Weisman <eliza@buoyant.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

tokio = { version = "1", features = ["sync", "time", "macros", "tracing"]}
tokio-stream = "0.1"
tonic = { version = "0.4", features = ["transport"] }
console-api = { path = "../console-api", features = ["transport"]}
tracing-core = "0.1.18"
tracing = "0.1.26"
tracing-subscriber = { version = "0.2.17", default-features = false, features = ["fmt", "registry"] }
futures = { version = "0.3", default-features = false }

[dev-dependencies]

tokio = { version = "1", features = ["full", "rt-multi-thread"]}
futures = "0.3"

tracing-subscriber = { version = "0.2.17", features = ["fmt", "registry", "env-filter"] }

[[example]]
name = "app"
path = "examples/app.rs"

[[example]]
name = "dump"
path = "examples/dump.rs"
