[package]
name = "console-subscriber"
version = "0.1.0"
authors = ["Eliza Weisman <eliza@buoyant.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

tokio = { version = "^1.10", features = ["sync", "time", "macros", "tracing"]}
tokio-stream = "0.1"
console-api = { path = "../console-api", features = ["transport"]}
tonic = { version = "0.5", features = ["transport"] }
tracing-core = "0.1.18"
tracing = "0.1.26"
tracing-subscriber = { version = "0.2.17", default-features = false, features = ["fmt", "registry", "env-filter"] }
futures = { version = "0.3", default-features = false }
hdrhistogram = { version = "7.3.0", default-features = false, features = ["serialization"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]

tokio = { version = "^1.7", features = ["full", "rt-multi-thread"]}
futures = "0.3"
