target_addr = 'http://127.0.0.1:6669/'
env_filter = 'info'
retain_for = '6s'

[charset]
lang = 'en_US.UTF-8'
ascii_only = false

[colors]
enabled = true
truecolor = true
palette = 'all'

[colors.enable]
durations = true
terminated = true
