target_addr = 'http://127.0.0.1:6669/'
retain_for = '6s'
log = 'info'

[charset]
lang = 'en_US.UTF-8'
ascii_only = false

[colors]
enabled = true
truecolor = true
palette = 'all'

[colors.enable]
durations = true
terminated = true
